package grupo2_tp6_c2;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.TreeSet;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
//import javax.swing.JDesktopPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author keter
 */
public class Ppal_SuperDeTodo_Ej2 extends javax.swing.JFrame {
    
    public static TreeSet<Producto_Ej2> listaProductos= new TreeSet<>();
    private EscritorioPersonalizado_Ej2 escritorio;

    
    public Ppal_SuperDeTodo_Ej2() {
        
        initComponents();
//        cargarProductos();
        escritorio= new EscritorioPersonalizado_Ej2();
        this.setContentPane(escritorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuAdmin = new javax.swing.JMenu();
        jAdminProductos = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jConsultaPrecio = new javax.swing.JMenuItem();
        jConsultaRubro = new javax.swing.JMenuItem();
        jConsultaNombre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuAdmin.setText("Administración");

        jAdminProductos.setText("Productos");
        jMenuAdmin.add(jAdminProductos);

        jMenuBar.add(jMenuAdmin);

        jMenuConsultas.setText("Consultas");

        jConsultaPrecio.setText("Por precio");
        jMenuConsultas.add(jConsultaPrecio);

        jConsultaRubro.setText("Por rubro");
        jMenuConsultas.add(jConsultaRubro);

        jConsultaNombre.setText("Por nombre");
        jConsultaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaNombreActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jConsultaNombre);

        jMenuBar.add(jMenuConsultas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConsultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaNombreActionPerformed
       
        escritorio.removeAll();
        escritorio.repaint();
        busquedaPorNombre bpn= new busquedaPorNombre();
        bpn.setVisible(true);
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
    }//GEN-LAST:event_jConsultaNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ppal_SuperDeTodo_Ej2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ppal_SuperDeTodo_Ej2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ppal_SuperDeTodo_Ej2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ppal_SuperDeTodo_Ej2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ppal_SuperDeTodo_Ej2().setVisible(true);
                new BusquedaPorNombre_Ej2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAdminProductos;
    private javax.swing.JMenuItem jConsultaNombre;
    private javax.swing.JMenuItem jConsultaPrecio;
    private javax.swing.JMenuItem jConsultaRubro;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConsultas;
    // End of variables declaration//GEN-END:variables

//private void cargarProductos(){
//    listaProductos.add(new Producto_Ej2(03, "Azucar x 1kg", 750, Categoria.COMESTIBLE));
//}

//public class EscritorioPersonalizado_Ej2 extends JDesktopPane{
//    private BufferedImage img;
//
//    public EscritorioPersonalizado_Ej2() {
//        try{
//            img=ImageIO.read(getClass().getResourceAsStream("/Recursos/imagesGP.png"));
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//    }
//   
//    
//    protected void paintComponent(Graphics g){
//        super.paintComponent(g);
//        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
//    }
//    
//    
//}
}
